### ISSUE TITLE
update broke

### ISSUE THREAD

**Issue by 0ldi** [ajaxvs/poeNullParticles#4]
Today update broke, no efffect in game

**Comment by ajaxvs** [comment]
Everything is fine as for me.
Are you talking about new patches that overwrite some effect files? It's ok. There's a message about it:
>Done.
>GGG can update some files during major patches.
>In that case launch this app again.

**Comment by 0ldi** [comment]
I dont know, everything worked yesterday, effects were successfully removed (even with minor patches), but today the "Make Good" button has no effect ...
This is the end of log
By the way, until today patсh, these errors were also there, but the effects in the game were still removed.
![image](https://user-images.githubusercontent.com/16578229/85765383-bb730280-b71e-11ea-92f7-b1990b47e40f.png)

**Comment by ajaxvs** [comment]
I see.
1. Close the game before modding client files. Logs are pretty clear: "Content.ggpk is using by another process". That's why the app does nothing.
2. Your backup folder is outdated. It's a good practice to restore all effects before league start and delete "backup" folder to get rid of "no record" messages.
3. Steam launcher checks game client and download original files before every game start. There's an option to avoid it but I don't know how. We just don't use Steam if we want to modify game files.

**Comment by 0ldi** [comment]
1.i tried: close game, close steam, close all poe apps that i use, nothing help with this... looks like the error refers to the poeNullEffects process itself ...
2.I deleted everything completely, and unpacked the new version of poeNullEffects in the new league.
3True for previous league, but in this league (before today patch) i play on steam \ nonsteam without effects (I myself did not understand why this happened)
So I don’t have any ideas why everything is broken now and how to fix it.

**Comment by ajaxvs** [comment]
Ok. So the root of the problem is access restriction. This is a very common Windows warning message:
>google.com/search?q="process+cannot+access+the+file+because+another+process"
>google.com/search?q="процесс+не+может+получить+доступ+к+файлу"

Usually users just need to reboot PC to fix it. You can also try to launch the app with "Run as admin". And make sure no other process is reading Content.ggpk. There were no other reports about such issue and the last patch changed nothing special, so I guess you should check your system for background processes.

**Comment by 0ldi** [comment]
https://youtu.be/V3BGeCQSlJw
> Usually users just need to reboot PC to fix it.

done

> You can also try to launch the app with "Run as admin".

done (in video) tried steam/nosteam no differences

> And make sure no other process is reading Content.ggpk.

done (in video) moved the file to show that only poeNullEffects.exe use it

The only thing I have not tried is to completely reinstall the Poe-client but right now the start of the league and I can not afford it 
My PC explode on 500% movespeed in blight/t16 about 90*C with GGG stupid effects :(

**Comment by ajaxvs** [comment]
Thanks for the video. As a developer I saw some interesting things.
Seems like it's really poeNullEffects-related issue, I'll try to figure out what happens.

You can try to use the older (2019) version: 
https://github.com/ajaxvs/poeNullParticles/releases/tag/190405
Just get the poeNullEffects.exe file from poeNullEffects_190405.zip, rename it (like "poeNullEffects_2019.exe") and put near the latest poeNullEffects.exe. So you can launch "poeNullEffects_2019.exe" and use the current backup.
The older version doesn't disable shadows but all other functions should work flawless.

**Comment by 0ldi** [comment]
tried 2019 no effect. so i reinstall PoE and it probably help...no errors. Some effects have not gone away, I see my aura and my main skill, although it is probably not bad, less suspicious. This is probably the best thing you can advise in such a situation.

**Comment by ajaxvs** [comment]
I think I found the problem. Fixed it in the temporary 200709 release.
