### ISSUE TITLE
Can't find Content.ggpk. Steam Client mode enabled.

### ISSUE THREAD

**Issue by 14091415** [ajaxvs/poeNullParticles#8]
Hi there, when I path to my PathOfExile_x64Steam.exe it says : Can't find Content.ggpk. Steam Client mode enabled.

**Comment by ajaxvs** [comment]
That's correct. Steam client has no .ggpk and the app detects it. 
So what's your issue?

**Comment by Alex1993-max** [comment]
So it is no longer possible to remove effects from the steam version?

**Comment by ajaxvs** [comment]
It's possible in private versions. Please read release notes: https://github.com/ajaxvs/poeNullParticles/releases
The reason is PoE changed almost everything we've used in 3.11- so I have to create a new methods from scratch: https://www.pathofexile.com/forum/view-thread/2933680
If you still have any questions about private version, use e-mail.

**Comment by ajaxvs** [comment]
Not an issue
